#!/bin/sh

start() {
  if [ `ip a | grep inet | wc -l` -gt 1 ]; then
    echo "Configuring date..."
    ntpd -q -p ntp.cesnet.cz
  else
    echo "No IP, skipping date config..."
  fi
}

restart() {
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|restart|stop}"
    exit 1
esac

exit $?
