#!/bin/sh

start() {
  echo "Starting apps..."

  # wait for network
  sleep 1
  # start network
  ifup eth0

  # set time
  if [ `ip a | grep inet | wc -l` -gt 1 ]; then
    echo "Configuring date..."
    ntpd -q -p ntp.cesnet.cz
  else
    echo "No IP, skipping date config..."
  fi

  # set default state
  /usr/bin/rfmctrl 192.168.0.10 9000 N1 > /dev/null 2&>1
  amixer sset 'Power Amplifier',0 19 > /dev/null 2&>1
  mkfifo /tmp/mplayer.fifo
  mplayer -idle -slave -input file=/tmp/mplayer.fifo > /dev/null 2&>1 &
  
  # mute stream
  echo "loadfile VAR=http://icecast8.play.cz/cro1-128.mp3" > /tmp/mplayer.fifo
  amixer sset 'Left Mixer Left DAC',0 on > /dev/null 2> /dev/null
  amixer sset 'Right Mixer Right DAC',0 on > /dev/null 2> /dev/null

  # start websocket server
  nohup /usr/sbin/websocketserver > /dev/null 2> /dev/null &
  
  # start cron
  mkdir -p /var/spool/cron/crontabs
  cp /etc/crond/root /var/spool/cron/crontabs
  crond
}

stop() {
  /usr/bin/rfmctrl 192.168.0.10 9000 N1 > /dev/null 2&>1
  /usr/bin/radio none
  killall websocketserver
  killall mplayer
  killall crond
  rm -rf /tmp/mplayer.fifo
  rm -rf /var/spool/cron
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|restart|stop}"
    exit 1
esac

exit $?
