#!/bin/sh

USE_WIFI=0

start() {
  echo "Starting apps..."

  if [ $USE_WIFI -eq 0 ]; then
    # wait for network
    sleep 1
    # start network
    ifup eth0
  else
    # wait for network
    sleep 2
    # start wpa
    wpa_supplicant -c /etc/wpa_supplicant.conf -B -D nl80211 -i wlan0
    # start network
    ifup wlan0
  fi

  # set time
  if [ `ip a | grep inet | wc -l` -gt 1 ]; then
    echo "Configuring date..."
    ntpd -q -p ntp.cesnet.cz
  else
    echo "No IP, skipping date config..."
  fi

  IP=`ip a | grep eth | grep inet | cut -d "/" -f 1 | grep -o '[^ ]*$'`
  sed "1s/.*/var ip=\"$IP\";/" /etc/websock.js > /usr/html/js/websock.js

  # set default state
  /usr/bin/rfmctrl 192.168.0.10 9000 N1 > /dev/null 2>&1
  amixer sset 'Power Amplifier',0 19 > /dev/null 2>&1
  mkfifo /tmp/mplayer.fifo
  mplayer -cache 500 -idle -slave -input file=/tmp/mplayer.fifo > /dev/null 2>&1 &
  
  # mute stream
  /usr/bin/radio none

  # start websocket server
  nohup /usr/sbin/websocketserver > /dev/null 2> /dev/null &
  
  # start cron
  mkdir -p /var/spool/cron/crontabs
  cp /etc/crond/root /var/spool/cron/crontabs
  crond
}

stop() {
  /usr/bin/rfmctrl 192.168.0.10 9000 N1 > /dev/null 2>&1
  /usr/bin/radio none
  killall websocketserver
  killall mplayer
  killall crond
  rm -rf /tmp/mplayer.fifo
  rm -rf /var/spool/cron
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|restart|stop}"
    exit 1
esac

exit $?
