#!/bin/sh
#
# Enable USB network
#

start() {
  ifup usb0
  udhcpd /etc/udhcpd.conf
}

stop() {
  killall udhcpd
  ifdown usb0
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|restart|stop}"
    exit 1
esac

exit $?
