#!/bin/sh
#
# Generate USB device
#

# general parameters
VID=0x1781
PID=0x0d00
CONFIG_PATH=/sys/kernel/config/usb_gadget
G=lichee
D="${CONFIG_PATH}/${G}"


start() {
  echo "Configuring USB device..."

  mkdir -p ${D}
  echo ${VID} > ${D}/idVendor
  echo ${PID} > ${D}/idProduct
  mkdir ${D}/strings/0x409
  echo "k4chn1k" > ${D}/strings/0x409/manufacturer
  cat /etc/product > ${D}/strings/0x409/product

  # new configuration
  mkdir ${D}/configs/c.1
  mkdir ${D}/configs/c.1/strings/0x409
  echo "config" > ${D}/configs/c.1/strings/0x409/configuration
  echo 500 > ${D}/configs/c.1/MaxPower

  # HID function
  mkdir -p ${D}/functions/hid.0
  echo 0 > ${D}/functions/hid.0/protocol
  echo 0 > ${D}/functions/hid.0/subclass
  echo 64 > ${D}/functions/hid.0/report_length
  echo -ne \\x06\\x00\\xFF\\x09\\x01\\xA1\\x01\\x19\\x01\\x29\\x40\\x15\\x00\\x26\\xFF\\x00\\x75\\x08\\x95\\x40\\x81\\x02\\x19\\x01\\x29\\x40\\x91\\x02\\xC0 > ${D}/functions/hid.0/report_desc

  # Net function
#  mkdir ${D}/functions/rndis.0

  # MSC function
#  mkdir ${D}/functions/mass_storage.0

  # add function to descriptor
#  ln -s ${D}/functions/rndis.0 ${D}/configs/c.1
  ln -s ${D}/functions/hid.0 ${D}/configs/c.1

  echo "Starting USB device..."
  cat /etc/usbdevice > ${D}/UDC
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    echo "Stopping USB gadget..."
    echo "" > ${D}/UDC
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|restart|stop}"
    exit 1
esac

exit $?
