#!/bin/sh

start() {
  echo "Starting CRDA..."

  crda
}

restart() {
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|restart}"
    exit 1
esac

exit $?
