#!/bin/sh

BUILD_PATH=../audio/build
TARGET_PATH=../audio/target

# store build time and info
echo USER=`uname -n` > ${TARGET_PATH}/etc/build
echo HOST_KERNEL_RELEASE=`uname -r` >> ${TARGET_PATH}/etc/build
echo HOST_KERNEL_VERSION=`uname -v` >> ${TARGET_PATH}/etc/build
echo BUILD_DATE=`date` >> ${TARGET_PATH}/etc/build

# remove triggerhappy config folder
if [ -d ${TARGET_PATH}/etc/triggerhappy ]; then
  rm -rf ${TARGET_PATH}/etc/triggerhappy
fi

# remove links from target fs
if [ -f ${TARGET_PATH}/linuxrc ]; then
  rm -rf ${TARGET_PATH}/linuxrc
fi

if [ -d ${TARGET_PATH}/lib32 ]; then
  rm -rf ${TARGET_PATH}/lib32
fi

if [ -d ${TARGET_PATH}/usr/lib32 ]; then
  rm -rf ${TARGET_PATH}/usr/lib32
fi
