#!/bin/sh
#
# Get time from NTP
#

start() {
  ntpd -p ntp.cesnet.cz
}

stop() {
  killall ntpd
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|restart|stop}"
    exit 1
esac

exit $?
