#!/bin/sh

start() {
  echo "Configuring ALSA sound device..."

  # load values for Audio
  alsactl restore 0
}

restart() {
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    alsactl store 0
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|restart|stop}"
    exit 1
esac

exit $?
