#!/bin/sh
#
# Mount boot partition
#

start() {
 mount /dev/mmcblk0p1 /boot 
}

stop() {
  umount /boot
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|restart|stop}"
    exit 1
esac

exit $?
