#!/bin/sh
#
# Load WiFi driver 
#

start() {
  modprobe rtl8812au
}

stop() {
  rmmod rtl8812au
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|restart|stop}"
    exit 1
esac

exit $?
