#!/bin/sh
#
# RTTY
#

[ -e /etc/default/rtty ] && . /etc/default/rtty

start() {
  rtty -I $RTTY_ID -d $RTTY_DESC -h $RTTY_HOST -p $RTTY_PORT -s -a -k /etc/rtty/key.pem -c /etc/rtty/cert.pem -C /etc/rtty/server.pem -D
}

stop() {
  killall rtty
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart|reload)
    restart
  ;;
  *)
    echo "Usage: $0 {start|restart|stop}"
    exit 1
esac

exit $?
