#!/bin/sh
#
# Start mDNS responder
#

case "$1" in
  start)
        printf "Starting mdnsd: "
        mdnsd
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  stop)
        printf "Stopping mdnsd: "
        kill `cat /var/run/mdnsd.pid`
        [ $? = 0 ] && echo "OK" || echo "FAIL"
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
